### ISSUE TITLE
Real World Location Matching Not Working

### ISSUE THREAD

**Issue by Acronyte** [bogstandard/rl-weather#13]
Hello,

I am trying to set up the location matching feature, but I'm running into problems. I generated a few OpenWeatherMap API keys for free after making an account on their website, but something is not working in the plugin - No matter what I type in for the location in the plugin config, I receive the message "Could not load weather data with given API key and/or location ________  {"cod":401, "message": "Invalid API key. Please see https://openweathermap.org/faq#error401 for more info."}

This message pops up for any location I type in, such as the example from the tooltip "London, UK", and also pops up no matter which API key I use. Generating a new one and using it does not make a difference.

**Comment by bogstandard** [comment]
Hi, assuming you solved it?

**Comment by Acronyte** [comment]
Hi, yes, working properly now. I didn't do anything in particular that fixed the issue, so I think the API key must not have been active at the time for whatever reason. When I reopened RuneLite several hours later, it was working just fine for whatever reason. Thanks for checking.
