### ISSUE TITLE
Sounds playing very loudly

### ISSUE THREAD

**Issue by JeauxyPatton** [bogstandard/rl-weather#20]
Hello, the weather sounds suddenly started working on my RuneLite client for this plug-in. It took me a couple minutes to figure out where the audio was coming from haha. It is fairly loud (at least, to me), but I don't want to turn it off completely. Can a feature be added to change the volume of the sound effects?
Thanks!

**Comment by bogstandard** [comment]
Hi, thanks for your report. The volume controls are bundled in the upcoming release.
