### ISSUE TITLE
Suggestion: Snow

### ISSUE THREAD

**Issue by Wynadorn** [bogstandard/rl-weather#4]
There's a cool snow effect when you take the fairy ring DKS, maybe you could use that.

**Comment by bogstandard** [comment]
Hey, nice idea if you're able to discover the IDs associated with the effect I'm happy to investigate. 

I've a concern that the effect might be locked to Members only, not sure how Jagex protect game effects/scenery that are Members only on F2P worlds. That could prove troublesome.

Keeping this open incase anyone has pointers.
