### ISSUE TITLE
Sound Effects Broken in Production Build

### ISSUE THREAD

**Issue by bogstandard** [bogstandard/rl-weather#6]
When installed via the Plugin Hub the sound effects do not work.

They do work when in development mode though, making this somewhat annoying to debug.

Any assistance is very welcome as I continue to try and debug this issue without spamming the Maintainers of the Plugin-Up with worthless patches.

There some discussion here: https://github.com/runelite/plugin-hub/pull/2209#issuecomment-999759665

**Comment by bogstandard** [comment]
Something it **_might_** be could be the WAV encoding, to get the sounds to come out in the Development mode to begin with I had to change the bitrate and make them mono. Unfortunately I can't remember _exactly_ what was done.

**Comment by ipkpjersi** [comment]
Yep, this is confirmed fixed now, I just tested it. We can probably update https://github.com/bogstandard/rl-weather/blob/master/README.md#call-for-help now to remove it. I'm still hoping to rewrite audio to use something like an mp3 library some time so we can also control volume etc.
